/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavDrawer: typeof import('./src/components/App/AppNavDrawer.vue')['default']
    AppTopBar: typeof import('./src/components/App/AppTopBar.vue')['default']
    BarChart: typeof import('./src/components/Core/BarChart.vue')['default']
    ChangePasswordDialog: typeof import('./src/components/Core/ChangePasswordDialog.vue')['default']
    ConfirmDialog: typeof import('./src/components/App/ConfirmDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PieChart: typeof import('./src/components/Core/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeAndLanguageControls: typeof import('./src/components/ThemeAndLanguageControls.vue')['default']
  }
}
